# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
env:
  flutter_channel: 'stable' # or: 'dev' or 'beta'
  flutter_version: '2.10.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend/codind
      
      - name: build apk
        run: flutter build apk
        working-directory: frontend/codind

      - name: Analyze project source
        run: dart analyze

